// Rocket API calls
export const FETCH_ROCKETS_PENDING = 'FETCH_ROCKETS_PENDING';
export const FETCH_ROCKETS_SUCCESS = 'FETCH_ROCKETS_SUCCESS';
export const FETCH_ROCKETS_ERROR = 'FETCH_ROCKETS_ERROR';

// Mission API calls
export const FETCH_MISSIONS_PENDING = 'FETCH_MISSIONS_PENDING';
export const FETCH_MISSIONS_SUCCESS = 'FETCH_MISSIONS_SUCCESS';
export const FETCH_MISSIONS_ERROR = 'FETCH_MISSIONS_SUCCESS';
export const SET_MISSIONS_ROCKET_FILTER = 'SET_MISSIONS_ROCKET_FILTER';
export const SET_MISSIONS_SEARCH_FILTER = 'SET_MISSIONS_SEARCH_FILTER';

// History API calls
export const FETCH_HISTORY_PENDING = 'FETCH_HISTORY_PENDING';
export const FETCH_HISTORY_SUCCESS = 'FETCH_HISTORY_SUCCESS';
export const FETCH_HISTORY_ERROR = 'FETCH_HISTORY_ERROR';
export const SET_HISTORY_SEARCH_FILTER = 'SET_HISTORY_SEARCH_FILTER';

// About Company API calls
export const FETCH_ABOUT_PENDING = 'FETCH_ABOUT_PENDING';
export const FETCH_ABOUT_SUCCESS = 'FETCH_ABOUT_SUCCESS';
export const FETCH_ABOUT_ERROR = 'FETCH_ABOUT_ERROR';
